### ISSUE TITLE
issue with run_tridesclous inside loop (on Windows)

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spikesorters#163]
Hi, I have been trying to run tridesclous inside a loop but some file is kept open and crash the next iteration. 

my code:
```
for n in files_nlist:
       file = 'F:\\sl_data_test\\{}_sim{}.npy'.format(type,n)
       timeseries = np.load(file)
       timeseries = np.reshape(timeseries, [1, timeseries.size])
       recording = se.NumpyRecordingExtractor(timeseries=timeseries, geom=geom, sampling_frequency=sr)
       sorting = so.run_tridesclous(recording,**w_par)
       se.MdaSortingExtractor.write_sorting(sorting=sorting, save_path='E:\\test\\td_sim{}.mda'.format(n))
```

The error:
```
...
  File "F:/GitHub/spikeslink_tests/run_tridesclus_blocks_si.py", line 38, in <module>
    sorting = so.run_tridesclous(recording,**w_par)
  File "F:\GitHub\spikesorters\spikesorters\sorterlist.py", line 298, in run_tridesclous
    return run_sorter('tridesclous', *args, **kwargs)
  File "F:\GitHub\spikesorters\spikesorters\sorterlist.py", line 84, in run_sorter
    verbose=verbose, delete_output_folder=delete_output_folder)
  File "F:\GitHub\spikesorters\spikesorters\tridesclous\tridesclous.py", line 74, in __init__
    BaseSorter.__init__(self, **kargs)
  File "F:\GitHub\spikesorters\spikesorters\basesorter.py", line 68, in __init__
    shutil.rmtree(str(output_folder))
  File "E:\programs\Anaconda3\envs\spikes_link\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\programs\Anaconda3\envs\spikes_link\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "E:\programs\Anaconda3\envs\spikes_link\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'F:\\GitHub\\sl_tests\\tridesclous_output\\channel_group_0\\catalogue_constructor\\all_peaks.raw'

```

**Comment by samuelgarcia** [comment]
This is because sorting handle some file in the tridesclous folder.

In a loop, you need to force a new folder at each iteration.
```python
    sorting = so.run_tridesclous(recording,output_folder='folder{}'.format(i), **w_par)
```
or too delete the folder after the writing to MDA.

**Comment by ferchaure** [comment]
> delete the folder after the writing to MDA

That will be a better solution (I have a limited disk space)  but without closing that python instance is not possible. I tried deleting _sorting_ but it doesn't close the files. Maybe a `__del__` method in the spikesorter wrapper can perform a tidy destruction of the instance?

**Comment by samuelgarcia** [comment]
In fact I forgot it but it is already included:

```python
sorting = so.run_tridesclous(recording, delete_output_folder=True, **w_par)
```

**Comment by alejoe91** [comment]
Hi guys! @ferchaure  if you pull the latest spikesorters the output folder is automatically deleted, if existing :) if that doesn't solve the issue then it's something else

**Comment by ferchaure** [comment]
Hi, alejo.
I'm using the last commit, and the error appears when that new method try to delete the folder

**Comment by samuelgarcia** [comment]
@alejoe91 : you put the delete_output_folder=True by deafult ?
I am totally not in favor of this!!!!

**Comment by alejoe91** [comment]
I see..deleting folders through Python on windows is unfortunately problematic :( not the first time this shows up.

@samuelgarcia no! If you run a sorter and the output folder already exists, it's overwritten (not deleted afterwards)

**Comment by samuelgarcia** [comment]
@alejoe91 : ok Isee.
unfortunatly if the folder contain memmap that are not release before then you are not annlowed to overwrite.

**Comment by samuelgarcia** [comment]
@ferchaure : in your case you need to use `delete_output_folder=True`

**Comment by samuelgarcia** [comment]
@alejoe91 : where is this behavior of overwritting ?

**Comment by alejoe91** [comment]
> @alejoe91 : where is this behavior of overwritting ?

https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/basesorter.py#L68

**Comment by samuelgarcia** [comment]
I did not notice. It is a bit dangerous.

**Comment by ferchaure** [comment]
I tried with `delete_output_folder=True` and got the same results. Some files on the folder are deleted but not all of them (probably the open ones).

**Comment by ferchaure** [comment]
all the *.raw remains on the folder and can't be deleted.

@samuelgarcia these files are opened using memmap? are they accessible in any way from the so.run_tridesclous output?

**Comment by samuelgarcia** [comment]
Oups.
Then it is a bug.
theses memmap files should be close when the internal object tridesclous datatio is deleted.
I will have a look.

**Comment by alejoe91** [comment]
Can it be the extractor?

**Comment by samuelgarcia** [comment]
Maybe. I though Iwas doing a copy to avoid the memmap handle. I check.

**Comment by samuelgarcia** [comment]
I got it.
the extractor handle the dataio.
I must patch it.

**Comment by samuelgarcia** [comment]
Not yet.
I will.

**Comment by samuelgarcia** [comment]
I have just push a PR in spikeextractors.
This should fix this bug.

**Comment by ferchaure** [comment]
Nice! Thanks samuel. I will test it in a few hours. 
This allows me to use tridesclous as a core for my tracking method :smile:   (I still have the issues with the filter's parameters and the multiple identical detections)

**Comment by ferchaure** [comment]
I got the same error as before :disappointed:

**Comment by samuelgarcia** [comment]
With `delete_output_folder=True` ?
Outch.
I need to test on windows.

**Comment by ferchaure** [comment]
> delete_output_folder=True

Yes, I tried that argument as well

**Comment by alejoe91** [comment]
@samuelgarcia I think this would be fixed by making a `__del__` method in the `TridescloussortingExtractor` that `del` all memmap objects!

**Comment by samuelgarcia** [comment]
@alejoe91 : it is not anymore necessary. In that case this is something else.
The instance of TridescloussortingExtractor do not handle anymore memmap or something like that.
I don't know what I have to test it on windows.
